- name: Проверить статус репликации
  community.mysql.mysql_query:
    login_user: "root"
    login_password: "{{ db_root_pass }}"
    query: "SHOW SLAVE STATUS"
  register: slave_status_result

- name: Вывести основные показатели репликации
  debug:
    var: slave_status_result.query_result[0]

- name: Конфигурация replication у Slave
  community.mysql.mysql_replication:
    mode: changeprimary
    primary_host: db_master
    primary_user: "{{ db_repl_user }}"
    primary_password: "{{ db_repl_password }}"
    primary_auto_position: 0
    login_host: 127.0.0.1
    login_user: root
    login_password: "{{ db_root_pass }}"
    login_port: 3307
    connection_name: ''
    master_auto_position: 0


- name: Запускаем slave
  community.mysql.mysql_query:
    login_host: 127.0.0.1
    login_port: 3307
    login_user: root
    login_password: "{{ db_root_pass }}"
    login_unix_socket: ""
    query: "START SLAVE;"

- name: Проверяем статус Slave
  community.mysql.mysql_query:
    login_host: 127.0.0.1
    login_user: root
    login_password: "{{ db_root_pass }}"
    login_port: 3307
    login_unix_socket: ""
    query: SHOW SLAVE STATUS
  register: replication_check

- name: Выводим статус Slave
  debug:
    var: replication_check.query_result