version: '3.3'
services:
  wordpress:
    image: wordpress:php8.1
    restart: always
    ports:
      - "80:80"
    volumes:
      - "wp_data:/var/www/html/"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress 
    depends_on:
      - db
      
  db:
    image: mysql:9.2.0
    restart: always
    volumes:
      - "db_data:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

volumes:
  wp_data:
  db_data: