- hosts: study-ansible
  become: true
  remote_user: user
  vars:
    db_user: wordpress
    db_password: wordpress
    db_name: wordpress
    db_root_pass: root
    docker_compose_dir: /home/user/wordpress
    db_repl_user: repl_user
    db_repl_password: repl_password
    docker_users: [ ubuntu,user ]
    mysql_port: 3306
  roles:
    - role: install-docker
    - role: wordpress
    - role: mysql-master
    - role: mysql-slave 